version: '3.1'
services:
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask
    container_name: flask
    volumes:
      - ./:/app/
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000

